name: flutter_onboarding_screen
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.3
  shared_preferences: ^2.2.3
  http: ^0.13.3
  firebase_core: any
  cloud_firestore: ^4.8.2
  firebase_auth: ^4.6.3
  firebase_storage: ^11.2.4
  image_picker: ^0.8.4+8
  file_picker: ^4.2.7
  js: 0.6.7
  cupertino_icons: ^1.0.2
  url_launcher: ^6.2.6
  flutter_pdfview: ^1.0.4+2
  permission_handler: ^10.2.0

<<<<<<< HEAD
  # cloud_firestore: ^4.17.4
dev_dependencies:
=======
dev_dependencies: 
>>>>>>> 929db3dc401bc4d85f39d801d565513fb57ec429
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/sosialmedia/
<<<<<<< HEAD
    - assets/images/poster1.jpg
    - assets/images/poster2.jpg
    - assets/images/poster3.jpg
    - assets/pdf/juknis.pdf
=======
    - assets/pdf/juknis.pdf
>>>>>>> 929db3dc401bc4d85f39d801d565513fb57ec429
